// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaec_vkPe8lA_7GH6snruYx8A1yfBqjn4',
    appId: '1:206480897735:web:115b35309d4f524397b0e2',
    messagingSenderId: '206480897735',
    projectId: 'mnnit-a08f6',
    authDomain: 'mnnit-a08f6.firebaseapp.com',
    storageBucket: 'mnnit-a08f6.appspot.com',
    measurementId: 'G-DYXXBWVBV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnRLZk5a4UjWQSSoVQA9iKXuIWRVl39m4',
    appId: '1:206480897735:android:37f8fd3b4d598bc397b0e2',
    messagingSenderId: '206480897735',
    projectId: 'mnnit-a08f6',
    storageBucket: 'mnnit-a08f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlx6g1Sl3qnL5vFWfZ__x7OqSuo1wUzuA',
    appId: '1:206480897735:ios:864b8db3958d714697b0e2',
    messagingSenderId: '206480897735',
    projectId: 'mnnit-a08f6',
    storageBucket: 'mnnit-a08f6.appspot.com',
    iosBundleId: 'com.example.mnnit',
  );
}
